version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - unused
    - govet
    - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
